#!/usr/bin/env python3
"""Aggregate sanitized, read-only provider-upgrade readiness and alerts."""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any

sys.path.insert(0, "/app")

from src.db.neo4j_db import Neo4jDB
from src.db.postgres import PostgresDB
from src.graphiti.operational_readiness import (
    OperationalThresholds,
    build_operational_readiness,
)
from src.graphiti.sync_profile import GraphSyncExecutionProfile
from src.graphiti.sync_state import GraphSyncRepository
from src.llm.provider_config import ProviderSettings, resolve_provider_settings
from src.scripts.embedding_preflight import collect_preflight
from src.scripts.graph_audit import collect_graph_audit
from src.scripts.graph_sync import json_default

MAX_BASELINE_BYTES = 5 * 1024 * 1024


def sanitized_configuration(
    settings: ProviderSettings,
    sync_profile: GraphSyncExecutionProfile,
) -> dict[str, Any]:
    """Expose selected identities and policies without endpoints or credentials."""
    return {
        "application_text": {
            "provider": settings.text_provider,
            "routes": {
                task: {
                    "models": [candidate.model for candidate in route.candidates],
                    "fingerprint": route.fingerprint,
                }
                for task, route in settings.text_routes.items()
            },
        },
        "application_embedding": settings.embedding_profile.sanitized_summary(),
        "graphiti_text": {
            "provider": settings.graphiti_text_provider,
            "models": [candidate.model for candidate in settings.graphiti_text_route.candidates],
            "fingerprint": settings.graphiti_text_route.fingerprint,
        },
        "graphiti_embedding": settings.graphiti_embedding_profile.sanitized_summary(),
        "graph_sync": sync_profile.sanitized_summary(),
    }


def load_baseline(path: Path | None) -> Mapping[str, Any] | None:
    """Load one bounded report generated by this command for growth comparison."""
    if path is None:
        return None
    stat = path.stat()
    if stat.st_size > MAX_BASELINE_BYTES:
        raise ValueError("Baseline readiness report is too large")
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, Mapping) or value.get("schema_version") != 1:
        raise ValueError("Baseline readiness report has an unsupported schema")
    graph_sync = value.get("graph_sync")
    if not isinstance(graph_sync, Mapping):
        raise ValueError("Baseline readiness report is incomplete")
    return value


async def collect_report(
    postgres: Any,
    neo4j: Any,
    *,
    settings: ProviderSettings,
    sync_profile: GraphSyncExecutionProfile,
    thresholds: OperationalThresholds,
    baseline_report: Mapping[str, Any] | None,
) -> dict[str, Any]:
    """Collect every component without provider calls or database mutations."""
    repository = GraphSyncRepository(postgres)
    sync_snapshot = await repository.status_snapshot()
    run_summary = sync_snapshot.get("latest_run_summary") or {
        "schema_version": 1,
        "status": "no_runs",
        "run": None,
    }
    quality_table_available = await postgres.fetchval(
        "SELECT to_regclass('public.graph_sync_relationship_quality') IS NOT NULL"
    )
    if quality_table_available:
        relationship_quality = await repository.relationship_quality_report()
    else:
        relationship_quality = {
            "schema_version": 1,
            "status": "unavailable",
            "reason": "relationship_quality_migration_pending",
            "run": None,
        }

    audit = await collect_graph_audit(
        postgres,
        neo4j,
        expected_sync_profile=sync_profile.sync_profile_fingerprint,
        expected_embedding_profile=sync_profile.embedding_profile_fingerprint,
    )
    embedding = await collect_preflight(
        postgres,
        "episodes",
        profile_resolver=lambda: settings.embedding_profile,
    )
    return build_operational_readiness(
        configuration=sanitized_configuration(settings, sync_profile),
        configured_sync_profile=sync_profile.sync_profile_fingerprint,
        sync_snapshot=sync_snapshot,
        run_summary=run_summary,
        relationship_quality=relationship_quality,
        graph_audit=audit,
        embedding_preflight=embedding,
        thresholds=thresholds,
        baseline_report=baseline_report,
    )


def render_human(report: Mapping[str, Any]) -> str:
    """Render one compact status view without episode IDs, text, or error detail."""
    graph_sync = report["graph_sync"]
    queue = graph_sync["queue"]
    counts = queue["counts"]
    latest_run = graph_sync["latest_run"]
    run = latest_run.get("run")
    audit = report["graph_audit"]
    embedding = report["embedding_preflight"]
    quality = graph_sync["relationship_quality"]
    alerts = report["alerts"]
    lines = [
        f"Operational readiness: {str(report['status']).upper()}",
        (
            "Graph queue: "
            f"total={queue['total']}, eligible={queue['eligible']}, "
            f"leased={counts.get('leased', 0)}, retry_wait={counts.get('retry_wait', 0)}, "
            f"quarantined={counts.get('quarantined', 0)}, "
            f"expired_leases={queue['expired_leases']}"
        ),
        f"Graph audit: {str(audit['status']).upper()} "
        f"(drift={audit['counts'].get('drift_findings', 0)})",
        f"Embedding preflight: {str(embedding['status']).upper()}",
        f"Relationship quality: {str(quality.get('status', 'unavailable')).upper()}",
    ]
    if isinstance(run, Mapping):
        progress = latest_run.get("progress") or {}
        provider_calls = latest_run.get("provider_calls") or {}
        lines.extend(
            (
                f"Latest run: {run.get('state')} ({run.get('sync_profile_fingerprint')})",
                "Run completion: "
                f"{progress.get('synced_jobs', 0)}/{progress.get('total_jobs', 0)} "
                f"({progress.get('completion_percent', 0)}%)",
                "Provider calls: "
                f"{provider_calls.get('completed', 0)}/{provider_calls.get('reserved', 0)} "
                "completed",
            )
        )
        for candidate in provider_calls.get("candidates", []):
            latency = candidate.get("latency_ms") or {}
            lines.append(
                "- Candidate "
                f"{candidate.get('provider')}/{candidate.get('model')}: "
                f"{candidate.get('completed', 0)}/{candidate.get('reserved', 0)} completed, "
                f"p95={latency.get('p95', 'unavailable')} ms"
            )
    else:
        lines.append("Latest run: none")

    lines.append(f"Alerts: critical={alerts['critical']}, warning={alerts['warning']}")
    for alert in alerts["items"]:
        lines.append(f"- {str(alert['severity']).upper()} {alert['code']}: {alert['message']}")
    lines.append("Scope: aggregate metadata only; no provider calls or state changes were made.")
    return "\n".join(lines)


async def run(
    args: argparse.Namespace,
    *,
    postgres_factory: Callable[..., Any] = PostgresDB,
    neo4j_factory: Callable[..., Any] = Neo4jDB,
    settings_resolver: Callable[[], ProviderSettings] = resolve_provider_settings,
    sync_profile_resolver: Callable[[], GraphSyncExecutionProfile] = (
        GraphSyncExecutionProfile.from_environment
    ),
    report_collector: Callable[..., Any] = collect_report,
) -> int:
    """Collect readiness with read-only clients and stable exit semantics."""
    postgres = None
    neo4j = None
    cleanup_error_type = None
    try:
        baseline_report = load_baseline(args.baseline_report)
        thresholds = OperationalThresholds(
            retry_storm_min_attempts=args.retry_storm_min_attempts,
            retry_storm_percent=args.retry_storm_percent,
            provider_failure_min_calls=args.provider_failure_min_calls,
            provider_failure_percent=args.provider_failure_percent,
        )
        settings = settings_resolver()
        sync_profile = sync_profile_resolver()
        postgres = postgres_factory(read_only=True)
        neo4j = neo4j_factory(read_only=True)
        await postgres.connect()
        await neo4j.connect()
        report = await report_collector(
            postgres,
            neo4j,
            settings=settings,
            sync_profile=sync_profile,
            thresholds=thresholds,
            baseline_report=baseline_report,
        )
    except Exception as error:
        incomplete = {
            "schema_version": 1,
            "status": "incomplete",
            "ready": False,
            "error_type": type(error).__name__,
            "message": "Operational readiness could not complete",
        }
        destination = sys.stdout if args.json else sys.stderr
        if args.json:
            print(json.dumps(incomplete, indent=2, sort_keys=True), file=destination)
        else:
            print(
                f"Operational readiness: INCOMPLETE ({incomplete['error_type']})",
                file=destination,
            )
        exit_code = 2
    else:
        if args.json:
            print(json.dumps(report, indent=2, sort_keys=True, default=json_default))
        else:
            print(render_human(report))
        exit_code = 0 if report["status"] == "ready" else 1
    finally:
        for client in (neo4j, postgres):
            if client is None:
                continue
            try:
                await client.disconnect()
            except Exception as error:
                cleanup_error_type = type(error).__name__

    if cleanup_error_type is not None:
        print(
            f"Operational readiness cleanup incomplete ({cleanup_error_type})",
            file=sys.stderr,
        )
        return 2
    return exit_code


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Read-only provider, graph, audit, embedding, and alert readiness"
    )
    parser.add_argument("--json", action="store_true", help="Emit stable JSON output")
    parser.add_argument(
        "--baseline-report",
        type=Path,
        help="Prior JSON report used only to detect quarantined-job growth",
    )
    parser.add_argument("--retry-storm-min-attempts", type=int, default=5)
    parser.add_argument("--retry-storm-percent", type=float, default=25.0)
    parser.add_argument("--provider-failure-min-calls", type=int, default=5)
    parser.add_argument("--provider-failure-percent", type=float, default=25.0)
    return parser


def main() -> int:
    return asyncio.run(run(build_parser().parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
