-- Validation History Tables for Luminari Sage
-- Stores validation reports and findings from PydanticAI agents

-- Create validation_reports table
CREATE TABLE IF NOT EXISTS validation_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id VARCHAR(255) UNIQUE NOT NULL,
    agent_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Report details
    validation_type VARCHAR(255) NOT NULL,
    scope_description TEXT NOT NULL,
    total_items_checked INTEGER NOT NULL DEFAULT 0,

    -- Summary statistics
    findings_count INTEGER NOT NULL DEFAULT 0,
    severity_counts JSONB NOT NULL DEFAULT '{}',
    category_counts JSONB NOT NULL DEFAULT '{}',

    -- Execution details
    execution_time_seconds DECIMAL(10, 3) NOT NULL DEFAULT 0,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT,

    -- Full markdown report for human review
    markdown_report TEXT,

    -- Metadata
    metadata JSONB DEFAULT '{}'
);

-- Create validation_findings table
CREATE TABLE IF NOT EXISTS validation_findings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    finding_id VARCHAR(255) UNIQUE NOT NULL,
    report_id UUID NOT NULL REFERENCES validation_reports(id) ON DELETE CASCADE,
    agent_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    -- Finding classification
    severity VARCHAR(50) NOT NULL CHECK (severity IN ('info', 'warning', 'error', 'critical')),
    category VARCHAR(255) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,

    -- Evidence and confidence
    confidence_score DECIMAL(3, 2) NOT NULL CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
    confidence_explanation TEXT NOT NULL,
    evidence JSONB NOT NULL DEFAULT '[]',

    -- Suggested actions
    suggested_action TEXT NOT NULL,
    priority INTEGER NOT NULL CHECK (priority >= 1 AND priority <= 5),

    -- Affected items
    affected_entities JSONB NOT NULL DEFAULT '[]',
    affected_relationships JSONB NOT NULL DEFAULT '[]',

    -- Human review tracking
    reviewed BOOLEAN NOT NULL DEFAULT FALSE,
    reviewer VARCHAR(255),
    review_timestamp TIMESTAMP WITH TIME ZONE,
    review_action VARCHAR(255),
    review_notes TEXT,

    -- Additional metadata
    metadata JSONB DEFAULT '{}'
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_validation_reports_agent_id ON validation_reports(agent_id);
CREATE INDEX IF NOT EXISTS idx_validation_reports_created_at ON validation_reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_validation_reports_validation_type ON validation_reports(validation_type);

CREATE INDEX IF NOT EXISTS idx_validation_findings_report_id ON validation_findings(report_id);
CREATE INDEX IF NOT EXISTS idx_validation_findings_agent_id ON validation_findings(agent_id);
CREATE INDEX IF NOT EXISTS idx_validation_findings_severity ON validation_findings(severity);
CREATE INDEX IF NOT EXISTS idx_validation_findings_category ON validation_findings(category);
CREATE INDEX IF NOT EXISTS idx_validation_findings_reviewed ON validation_findings(reviewed);
CREATE INDEX IF NOT EXISTS idx_validation_findings_priority ON validation_findings(priority);
CREATE INDEX IF NOT EXISTS idx_validation_findings_created_at ON validation_findings(created_at DESC);

-- Create GIN indexes for JSONB columns for efficient searching
CREATE INDEX IF NOT EXISTS idx_validation_reports_severity_counts_gin ON validation_reports USING GIN (severity_counts);
CREATE INDEX IF NOT EXISTS idx_validation_reports_category_counts_gin ON validation_reports USING GIN (category_counts);
CREATE INDEX IF NOT EXISTS idx_validation_findings_evidence_gin ON validation_findings USING GIN (evidence);
CREATE INDEX IF NOT EXISTS idx_validation_findings_affected_entities_gin ON validation_findings USING GIN (affected_entities);
CREATE INDEX IF NOT EXISTS idx_validation_findings_affected_relationships_gin ON validation_findings USING GIN (affected_relationships);

-- Add helpful comments
COMMENT ON TABLE validation_reports IS 'Stores validation reports generated by PydanticAI agents for Luminari Sage knowledge graph validation';
COMMENT ON TABLE validation_findings IS 'Stores individual validation findings with audit trails and human review tracking';
COMMENT ON COLUMN validation_findings.severity IS 'Severity level: info, warning, error, critical';
COMMENT ON COLUMN validation_findings.priority IS 'Priority level: 1 (highest) to 5 (lowest)';
COMMENT ON COLUMN validation_findings.confidence_score IS 'Confidence score from 0.0 to 1.0 indicating agent certainty';
COMMENT ON COLUMN validation_findings.reviewed IS 'Whether this finding has been reviewed by a human';

-- Grant permissions (adjust as needed for your setup)
-- GRANT SELECT, INSERT, UPDATE ON validation_reports TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE ON validation_findings TO your_app_user;
